---
# tasks file for zabbix

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: zabbix

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags: zabbix

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: zabbix

- name: Create Zabbix agent configuration
  template: >
    src=zabbix_agentd.conf.j2
    dest=/etc/zabbix/zabbix_agentd.conf
    owner=root
    group=root
    mode=0644
  notify: restart zabbix agent
  tags: zabbix

- name: Ensure Zabbix agent service is started and enabled on boot
  service: name={{ zabbix_agent_service_name }} state=started enabled=yes
  tags: zabbix
