---
# tasks file for zabbix (Ubuntu specific)

- name: Add Zabbix APT key
  apt_key: >
    url=http://repo.zabbix.com/zabbix-official-repo.key
    state=present
  tags: zabbix

- name: Create Zabbix APT repository
  apt_repository: >
    repo='deb http://repo.zabbix.com/zabbix/{{ zabbix_version }}/ubuntu trusty main'
    state=present
  tags: zabbix

- name: Install Zabbix agent packages
  apt: name={{ item }} state=latest update_cache=yes
  with_items: zabbix_agent_packages
  tags: zabbix
